# Generated by Django 4.1 on 2022-08-26 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(max_length=250)),
                ('requester', models.CharField(max_length=100)),
                ('secretária_Setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='called.secretary')),
            ],
        ),
    ]
