# Generated by Django 4.2.30 on 2026-09-30 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secretary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secretary_name",
                    models.CharField(max_length=255, verbose_name="Secretaria"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sector_name", models.CharField(max_length=255, verbose_name="Setor")),
                (
                    "secretary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setores",
                        to="called.secretary",
                        verbose_name="Seceretaria do setor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem", models.TextField(max_length=250, verbose_name="Problema")),
                (
                    "requester",
                    models.CharField(max_length=250, verbose_name="Requisitante"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPN", "Aberto"),
                            ("IMP", "Em andamento"),
                            ("CLS", "Encerrado"),
                        ],
                        default="OPN",
                        max_length=3,
                        verbose_name="Status do Chamado",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (0, "Prioridade Alta"),
                            (1, "Prioridade Média"),
                            (2, "Prioridade Baixa"),
                        ],
                        default=1,
                        verbose_name="Prioridade do chamado",
                    ),
                ),
                ("date_start", models.DateField(default=django.utils.timezone.now)),
                ("date_end", models.DateField(blank=True, default=None, null=True)),
                (
                    "solution",
                    models.TextField(
                        blank=True, max_length=250, null=True, verbose_name="Solução"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="called.sector",
                        verbose_name="Setor",
                    ),
                ),
                (
                    "tecs",
                    models.ManyToManyField(
                        blank=True, related_name="chamados", to="core.tecs"
                    ),
                ),
            ],
        ),
    ]
