# Generated by Django 4.2.30 on 2026-06-08 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretarySector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem", models.TextField(max_length=250, verbose_name="Problema")),
                (
                    "requester",
                    models.CharField(max_length=100, verbose_name="Requisitante"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPN", "abertos"),
                            ("IMP", "emAndamento"),
                            ("CLS", "encerrados"),
                        ],
                        default="OPN",
                        max_length=3,
                        verbose_name="Status do Chamado",
                    ),
                ),
                ("date_start", models.DateField(default=django.utils.timezone.now)),
                ("date_end", models.DateField(blank=True, default=None, null=True)),
                (
                    "solution",
                    models.TextField(
                        blank=True, max_length=250, null=True, verbose_name="Solução"
                    ),
                ),
                (
                    "secretary_sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="called.secretarysector",
                    ),
                ),
            ],
        ),
    ]
