# Generated by Django 6.0.6 on 2026-06-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("called", "0002_secretarysector_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="technician",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="calls", to="called.technician"
            ),
        ),
    ]
