# Generated by Django 4.1 on 2022-08-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0002_call'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='secretária_Setor',
            new_name='secretary_sector',
        ),
    ]
