# Generated by Django 4.1 on 2022-09-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0003_rename_secretária_setor_call_secretary_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('OPN', 'Aberto'), ('INP', 'Em Processo'), ('CLS', 'Encerado')], default='OPN', max_length=3),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
