# Generated by Django 4.1 on 2022-12-15 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0004_call_status_alter_secretary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('OPN', 'abertos'), ('IMP', 'emAndamento'), ('CLS', 'encerrados')], default='OPN', max_length=3),
        ),
    ]
