# Generated by Django 4.1 on 2022-12-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0005_call_date_alter_call_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='date',
            new_name='date_start',
        ),
        migrations.AddField(
            model_name='call',
            name='date_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
