# Generated by Django 4.1 on 2022-12-17 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('called', '0006_rename_date_call_date_start_call_date_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tecnico', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
