# Generated by Django 4.1 on 2022-12-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0007_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='called',
            field=models.ManyToManyField(to='called.call'),
        ),
    ]
