# Generated by Django 4.1 on 2022-12-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0010_alter_tecnico_called'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='called',
            field=models.ManyToManyField(related_name='call_tecnico', to='called.call'),
        ),
    ]
