# Generated by Django 4.1 on 2022-12-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0012_alter_tecnico_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='solution',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
