# Generated by Django 4.1 on 2023-10-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0005_alter_call_status'),
        ('called', '0013_call_solution'),
    ]

    operations = [
    ]
