# Generated by Django 4.1 on 2023-10-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0014_merge_0005_alter_call_status_0013_call_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='problem',
            field=models.TextField(max_length=250, verbose_name='Problema'),
        ),
        migrations.AlterField(
            model_name='call',
            name='requester',
            field=models.CharField(max_length=100, verbose_name='Requisitante'),
        ),
    ]
