# Generated by Django 4.1 on 2024-11-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('called', '0015_alter_call_problem_alter_call_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='solution',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Solução'),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('OPN', 'abertos'), ('IMP', 'emAndamento'), ('CLS', 'encerrados')], default='OPN', max_length=3, verbose_name='Status do Chamado'),
        ),
    ]
