# Generated by Django 4.1 on 2023-10-10 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('called', '0015_alter_call_problem_alter_call_requester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='FichaVerificacaoComponentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField(default=django.utils.timezone.now, verbose_name='data do recebimento')),
                ('numero_tombo', models.CharField(default='', max_length=10, verbose_name='Número do tombo')),
                ('deixado', models.CharField(blank=True, default='', max_length=50, verbose_name='Deixado e conferido por')),
                ('recebido', models.CharField(blank=True, default='', max_length=50, verbose_name='Recebido por')),
                ('setor', models.CharField(blank=True, default='', max_length=50, verbose_name='Setor')),
                ('responsavel_pc', models.CharField(blank=True, default='', max_length=50, verbose_name='Responsável pelo PC')),
                ('descricao_problema', models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição do Problema')),
                ('observacao', models.TextField(blank=True, default='', max_length=300, verbose_name='Observações')),
                ('servico_realizado', models.TextField(blank=True, default='', max_length=300, verbose_name='Serviço Realizado')),
                ('buscado_por', models.CharField(blank=True, default='', max_length=50, verbose_name='Entrege e conferido por')),
                ('entrege_por', models.CharField(blank=True, default='', max_length=50, verbose_name='Entrege por')),
                ('laudo', models.CharField(default='', max_length=10, verbose_name='Número do Laudo')),
                ('data_entrega', models.DateField(default=None, null=True, verbose_name='data da entrega')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='called.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(1, 'Contêm e bom estado'), (2, 'Contêm e mau estado'), (3, 'Não comtêm')], default=3, verbose_name='Comtêm e o estado')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed.componente')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed.fichaverificacaocomponentes')),
            ],
        ),
    ]
