# Generated by Django 4.2.30 on 2026-06-08 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("called", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="Nome"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="data do recebimento",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        default="", max_length=30, verbose_name="Número do tombo/série"
                    ),
                ),
                (
                    "left_by",
                    models.CharField(
                        default="",
                        max_length=50,
                        verbose_name="Deixado e conferido por",
                    ),
                ),
                (
                    "pc_responsible",
                    models.CharField(
                        default="", max_length=50, verbose_name="Responsável pelo PC"
                    ),
                ),
                (
                    "problem_description",
                    models.CharField(
                        default="", max_length=200, verbose_name="Descrição do Problema"
                    ),
                ),
                ("contact", models.CharField(max_length=50, verbose_name="Contato")),
                (
                    "observation",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=300,
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
                (
                    "realized_service",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=300,
                        null=True,
                        verbose_name="Serviço Realizado",
                    ),
                ),
                (
                    "search_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        null=True,
                        verbose_name="Entrege e conferido por",
                    ),
                ),
                (
                    "report",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        null=True,
                        verbose_name="Número do Laudo",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="data da entrega",
                    ),
                ),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregue_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recebido_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secretary_sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="called.secretarysector",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="called.technician",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Contêm e bom estado"),
                            (2, "Contêm e mau estado"),
                            (3, "Não contêm"),
                        ],
                        verbose_name="Contêm e o estado",
                    ),
                ),
                (
                    "description_report",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Observação e descrição"
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fixed.component",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fixed.maintenancesheet",
                    ),
                ),
            ],
        ),
    ]
