# Generated by Django 6.0.6 on 2026-06-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixed", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Component",
            new_name="Components",
        ),
        migrations.RenameModel(
            old_name="ComponentStatus",
            new_name="Maintenance",
        ),
    ]
