# Generated by Django 4.1 on 2023-10-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='nome',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nome'),
        ),
    ]
