# Generated by Django 4.1 on 2023-10-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed', '0002_alter_componente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenteestado',
            name='observacao_descricao',
            field=models.CharField(default='', max_length=30, verbose_name='Observação e descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componenteestado',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Contêm e bom estado'), (2, 'Contêm e mau estado'), (3, 'Não comtêm')], default=3, verbose_name='Contêm e o estado'),
        ),
    ]
