# Generated by Django 6.0.6 on 2026-06-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixed", "0002_rename_component_components_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Maintenance",
            new_name="ComponentStatus",
        ),
    ]
