# Generated by Django 6.0.6 on 2026-06-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixed", "0003_rename_maintenance_componentstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentstatus",
            name="sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components_status",
                to="fixed.maintenancesheet",
            ),
        ),
    ]
