# Generated by Django 4.1 on 2023-10-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed', '0003_componenteestado_observacao_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenteestado',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Contêm e bom estado'), (2, 'Contêm e mau estado'), (3, 'Não contêm')], verbose_name='Contêm e o estado'),
        ),
        migrations.AlterField(
            model_name='componenteestado',
            name='observacao_descricao',
            field=models.CharField(max_length=20, null=True, verbose_name='Observação e descrição'),
        ),
        migrations.AlterField(
            model_name='fichaverificacaocomponentes',
            name='buscado_por',
            field=models.CharField(default='', max_length=50, verbose_name='Entrege e conferido por'),
        ),
        migrations.AlterField(
            model_name='fichaverificacaocomponentes',
            name='deixado',
            field=models.CharField(default='', max_length=50, verbose_name='Deixado e conferido por'),
        ),
        migrations.AlterField(
            model_name='fichaverificacaocomponentes',
            name='descricao_problema',
            field=models.CharField(default='', max_length=200, verbose_name='Descrição do Problema'),
        ),
        migrations.AlterField(
            model_name='fichaverificacaocomponentes',
            name='entrege_por',
            field=models.CharField(default='', max_length=50, verbose_name='Entrege por'),
        ),
        migrations.AlterField(
            model_name='fichaverificacaocomponentes',
            name='observacao',
            field=models.TextField(default='', max_length=300, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='fichaverificacaocomponentes',
            name='recebido',
            field=models.CharField(default='', max_length=50, verbose_name='Recebido por'),
        ),
        migrations.AlterField(
            model_name='fichaverificacaocomponentes',
            name='responsavel_pc',
            field=models.CharField(default='', max_length=50, verbose_name='Responsável pelo PC'),
        ),
        migrations.AlterField(
            model_name='fichaverificacaocomponentes',
            name='servico_realizado',
            field=models.TextField(default='', max_length=300, verbose_name='Serviço Realizado'),
        ),
        migrations.AlterField(
            model_name='fichaverificacaocomponentes',
            name='setor',
            field=models.CharField(default='', max_length=50, verbose_name='Setor'),
        ),
    ]
