# Generated by Django 4.1 on 2024-11-21 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixed', '0004_alter_componenteestado_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Setor')),
            ],
        ),
        migrations.AlterField(
            model_name='fichaverificacaocomponentes',
            name='recebido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fichaverificacaocomponentes',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed.setor'),
        ),
    ]
