# Generated by Django 4.1 on 2024-11-21 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixed', '0005_setor_alter_fichaverificacaocomponentes_recebido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaverificacaocomponentes',
            name='entrege_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrege_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fichaverificacaocomponentes',
            name='recebido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebido_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
