# Generated by Django 4.1 on 2025-10-16 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('called', '0016_alter_call_solution_alter_call_status'),
        ('fixed', '0006_alter_fichaverificacaocomponentes_entrege_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaDeManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField(default=django.utils.timezone.now, verbose_name='data do recebimento')),
                ('numero_tombo', models.CharField(default='', max_length=30, verbose_name='Número do tombo/série')),
                ('deixado', models.CharField(default='', max_length=50, verbose_name='Deixado e conferido por')),
                ('responsavel_pc', models.CharField(default='', max_length=50, verbose_name='Responsável pelo PC')),
                ('descricao_problema', models.CharField(default='', max_length=200, verbose_name='Descrição do Problema')),
                ('contato', models.CharField(max_length=50, verbose_name='Contato')),
                ('observacao', models.TextField(default='', max_length=300, null=True, verbose_name='Observações')),
                ('servico_realizado', models.TextField(default='', max_length=300, null=True, verbose_name='Serviço Realizado')),
                ('buscado_por', models.CharField(default='', max_length=50, null=True, verbose_name='Entrege e conferido por')),
                ('laudo', models.CharField(default='', max_length=10, null=True, verbose_name='Número do Laudo')),
                ('data_entrega', models.DateField(default=None, null=True, verbose_name='data da entrega')),
                ('entrege_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrege_por', to=settings.AUTH_USER_MODEL)),
                ('recebido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebido_por', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed.setor')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='called.tecnico')),
            ],
        ),
        migrations.AlterField(
            model_name='componenteestado',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed.fichademanutencao'),
        ),
        migrations.DeleteModel(
            name='FichaVerificacaoComponentes',
        ),
    ]
